### ISSUE TITLE
Req: Hide Y-M-D titles - metric date formats

### ISSUE THREAD

**Issue by skuske** [91renb/BRPickerView#123]
1.) How can I hide the Y-M-D titles?

![date_type1](https://user-images.githubusercontent.com/12996815/73726887-a4605380-4730-11ea-9bac-1f8994cc1ebb.png)

2.) I would like to suggest metric date formats. like D-M-Y and M-Y for example.

Thanks! :o)

**Comment by 91renb** [comment]
```
BRDatePickerView *datePickerView = [[BRDatePickerView alloc]init];
datePickerView.pickerMode = BRDatePickerModeDate;
datePickerView.minDate = [NSDate br_setYear:1948 month:10 day:1];
datePickerView.maxDate = [NSDate date];
datePickerView.isAutoSelect = YES;
datePickerView.resultBlock = ^(NSDate *selectDate, NSString *selectValue) {
    NSLog(@"selectValue=%@", selectValue);
};
```
![image](https://user-images.githubusercontent.com/23326671/73735601-7bfd4700-477a-11ea-8e9d-cedfa8135515.png)

**Comment by skuske** [comment]
@91renb 

Yes, I now that it works for BRDatePickerModeDate, but I would need it for `BRDatePickerModeYM`

**Comment by skuske** [comment]
![date_type10](https://user-images.githubusercontent.com/12996815/73736412-03c65f80-4741-11ea-9c8c-e9d71c7891ef.png)

**Comment by 91renb** [comment]
```
// hidden unit
datePickerView.showUnitType = BRShowUnitTypeNone;
```

**Comment by skuske** [comment]
Thanks, I missed that.

**Comment by skuske** [comment]
@91renb 

Any chance that metric date formats will be supported soon?

D-M-Y and M-Y for example, instead of Y-M-D and Y-M as those formats are not used on metric systems... Many thanks!

**Comment by 91renb** [comment]
It has been resolved and will be updated later.

**Comment by 91renb** [comment]
# D-M-Y
```
BRDatePickerView *datePickerView = [[BRDatePickerView alloc]init];
datePickerView.pickerMode = BRDatePickerModeDate;
datePickerView.resultBlock = ^(NSDate *selectDate, NSString *selectValue) {
    NSLog(@"selectDate=%@", selectDate);
};

BRPickerStyle *customStyle = [[BRPickerStyle alloc]init];
customStyle.language = @"en-GB";
datePickerView.pickerStyle = customStyle;

[datePickerView show];
```
![image](https://user-images.githubusercontent.com/23326671/75340192-fed27700-58cc-11ea-934a-4f47d91ab948.png)


# M-Y
```
BRDatePickerView *datePickerView = [[BRDatePickerView alloc]init];
datePickerView.pickerMode = BRDatePickerModeYM;
//datePickerView.monthNameType = BRMonthNameTypeFullName;
datePickerView.resultBlock = ^(NSDate *selectDate, NSString *selectValue) {
    NSLog(@"selectDate=%@", selectDate);
};
[datePickerView show];
```
![image](https://user-images.githubusercontent.com/23326671/75339848-43a9de00-58cc-11ea-80b2-b3b534fb299b.png)

**Comment by skuske** [comment]
This is still not working for

`BRDatePickerModeYMDHM`

On metric systems it still shows Year, Month, Day, but it should show Day, Month, Year

**Comment by agiapp** [comment]
`BRDatePickerModeYMDHM` does not currently support displaying day, month, year.
Currently, only `BRDatePickerModeYMD` and `BRDatePickerModeYM` support British date display. 
If you need to display `yyyy-MM-dd HH:mm`, you can use `BRDatePickerModeDateAndTime`.
